/* App shell + router wiring + the guided first path. */

import { h, clear } from "./lib/dom.js";
import { startRouter, onRoute, parseRoute } from "./lib/router.js";
import { RUNS, getRun } from "./lib/bundle.js";
import { verdictChip, btn, pill, panel, stateClass } from "./components/kit.js";
import { renderGallery } from "./surfaces/gallery.js";
import { renderReport } from "./surfaces/report.js";
import { renderVerifier } from "./surfaces/verifier.js";
import { renderCi } from "./surfaces/ci.js";
import { renderCompare } from "./surfaces/compare.js";

const GUIDE = [
  { route: "#/", copy: "Six real runs, produced by the CLI. Start with the pair that carries the argument." },
  { route: "#/compare", copy: "Same script, same gate. One checkpoint resumes the run; the other only looks like it does." },
  { route: "#/run/hf-model-only", copy: "Here is why it failed — optimizer, scheduler and RNG state were never persisted." },
  { route: "#/run/hf-complete/verify", copy: "Now check the proof yourself: your browser re-hashes every file, then try to break it." },
  { route: "#/run/hf-model-only/ci", copy: "And the same evidence as a pull-request check that blocks the merge." },
];

const GUIDE_KEY = "flashpilot.guide.dismissed";

const chipSlot = h("div", {});
const main = h("main", { class: "shell-main", id: "main", tabindex: "-1" });
const guideSlot = h("div", {});

function nav(route) {
  const runId = route.name === "run" ? route.runId : null;
  const links = [
    ["Gallery", "#/", route.name === "gallery"],
    ["Compare", "#/compare", route.name === "compare"],
  ];
  if (runId) {
    links.push(
      ["Report", `#/run/${runId}`, route.name === "run" && route.tab === "report"],
      ["Verify", `#/run/${runId}/verify`, route.name === "run" && route.tab === "verify"],
      ["CI", `#/run/${runId}/ci`, route.name === "run" && route.tab === "ci"],
    );
  }
  links.push(["About", "#/about", route.name === "about"]);

  return h(
    "nav",
    { class: "shell-nav", "aria-label": "surfaces" },
    ...links.map(([label, href, current]) =>
      h("a", { class: "nav-link", href, "aria-current": current ? "page" : null, text: label }),
    ),
  );
}

function renderAbout() {
  return h(
    "div",
    { class: "stack" },
    h(
      "header",
      { class: "stack-tight" },
      h("p", { class: "eyebrow", text: "about this surface" }),
      h("h1", { text: "What this page is allowed to do" }),
    ),
    panel(
      "Boundaries",
      {},
      h(
        "ul",
        { class: "lede", style: "margin:0;padding-left:1.1rem" },
        h("li", { text: "It never computes or overrides a verdict. Every status is copied from the CLI's typed output." }),
        h("li", { text: "It re-verifies by recomputing SHA-256 over raw evidence bytes with the browser's Web Crypto, independent of any JSON canonicalisation." }),
        h("li", { text: "It fails closed: unknown, missing, path-escaping or hash-mismatched evidence is never rendered as a pass." }),
        h("li", { text: "It ships as static files with no backend. Sample bytes are embedded, so once the page has loaded it makes no further network request." }),
        h("li", { text: "Nothing here is generated by a model, and no metric on any surface was invented." }),
      ),
    ),
    panel(
      "Where the data comes from",
      {},
      h(
        "p",
        { class: "lede", style: "margin-bottom:var(--s-4)" },
        "Each sample is a byte-for-byte copy of a real run directory. The mapping is recorded in each ",
        h("span", { class: "mono", text: "samples/<id>/SOURCE.txt" }),
        " and reproduced by ",
        h("span", { class: "mono", text: "tools/build_samples.py" }),
        ".",
      ),
      ...RUNS.map((run) =>
        h(
          "div",
          { class: `compare-metric ${stateClass(run.state)}` },
          h("span", {}, h("span", { class: "mono", text: `samples/${run.id}` })),
          h("span", { class: "v", text: `runs/${run.sourceRun}` }),
        ),
      ),
    ),
    panel(
      "Reproduce it locally",
      {},
      h(
        "div",
        { class: "stack-tight" },
        h("div", { class: "mono", text: "pip install 'flashpilot[hf]'" }),
        h("div", { class: "mono", text: "flashpilot demo" }),
        h("div", { class: "mono", text: "python -m http.server --directory report-ui" }),
      ),
    ),
  );
}

function runSurface(route) {
  const run = getRun(route.runId);
  if (!run) {
    return h(
      "div",
      { class: "stack" },
      h("h1", { text: "No such run" }),
      h("p", { class: "lede", text: `There is no sample called "${route.runId}" in this sandbox.` }),
      btn("Back to the gallery", { href: "#/", primary: true }),
    );
  }
  if (route.tab === "verify") return renderVerifier(run);
  if (route.tab === "ci") return renderCi(run);
  return renderReport(run);
}

function currentRun(route) {
  if (route.name === "run") return getRun(route.runId);
  if (route.name === "compare") return getRun(route.params?.get("a") ?? "hf-model-only");
  return null;
}

function renderGuide(route) {
  if (sessionStorage.getItem(GUIDE_KEY) === "1") return null;
  const index = GUIDE.findIndex((step) => matchesGuide(step.route, route));
  const step = index === -1 ? null : GUIDE[index];
  if (!step) return null;
  const next = GUIDE[index + 1];

  return h(
    "div",
    { class: "guide" },
    h("span", { class: "guide-step", text: `${index + 1}/${GUIDE.length}` }),
    h("p", { class: "guide-copy", text: step.copy }),
    h(
      "div",
      { class: "guide-actions" },
      next ? btn("Next", { href: next.route, primary: true }) : btn("Explore freely", { href: "#/" }),
      btn("Dismiss", {
        onClick: () => {
          sessionStorage.setItem(GUIDE_KEY, "1");
          clear(guideSlot);
        },
      }),
    ),
  );
}

function matchesGuide(guideRoute, route) {
  const target = parseRoute(guideRoute);
  if (target.name !== route.name) return false;
  if (target.name !== "run") return true;
  return target.runId === route.runId && (target.tab ?? "report") === (route.tab ?? "report");
}

function render(route) {
  clear(chipSlot).append(verdictChip(currentRun(route)));

  const header = document.querySelector(".shell-header");
  const oldNav = header.querySelector(".shell-nav");
  const newNav = nav(route);
  if (oldNav) header.replaceChild(newNav, oldNav);
  else header.append(newNav);

  clear(main);
  if (route.name === "gallery") main.append(renderGallery());
  else if (route.name === "compare") main.append(renderCompare(route.params));
  else if (route.name === "about") main.append(renderAbout());
  else main.append(runSurface(route));

  clear(guideSlot);
  const guide = renderGuide(route);
  if (guide) guideSlot.append(guide);

  window.scrollTo({ top: 0, behavior: "instant" });
  document.title = titleFor(route);
}

function titleFor(route) {
  const run = currentRun(route);
  if (run) return `${run.verdict} · ${run.title} — FlashPilot`;
  return "FlashPilot — resume qualification report";
}

export function mount(root) {
  const header = h(
    "header",
    { class: "shell-header" },
    h("a", { class: "brand", href: "#/" }, "FlashPilot", h("span", { text: "RESUME QUALIFICATION" })),
    chipSlot,
  );

  const restart = btn("Restart guided tour", {
    onClick: () => {
      sessionStorage.removeItem(GUIDE_KEY);
      if (window.location.hash === "#/") render(parseRoute());
      else window.location.hash = "#/";
    },
  });

  const footer = h(
    "footer",
    { class: "shell-footer" },
    h("span", { text: "Frameworks save checkpoints. FlashPilot proves they can resume." }),
    h(
      "span",
      { class: "row" },
      restart,
      pill("static · no backend", "neutral"),
      pill("verdicts copied, never computed", "data"),
    ),
  );

  root.append(
    h("a", { class: "skip-link", href: "#main", text: "Skip to content" }),
    header,
    main,
    guideSlot,
    footer,
  );

  onRoute(render);
  startRouter();
}
