"""Assign an ACL-isolated UUID basetemp before pytest creates TempPathFactory."""

from __future__ import annotations

import tempfile
import uuid
from pathlib import Path
from shutil import rmtree

import pytest

_GENERATED_BASETEMP = pytest.StashKey[Path]()


@pytest.hookimpl(tryfirst=True)
def pytest_configure(config: pytest.Config) -> None:
    """Set one unique direct temp child unless the caller supplied --basetemp."""

    if config.option.basetemp is not None:
        return
    basetemp = Path(tempfile.gettempdir()) / f"flashpilot-pytest-{uuid.uuid4().hex}"
    config.option.basetemp = basetemp
    config.stash[_GENERATED_BASETEMP] = basetemp


@pytest.hookimpl(trylast=True)
def pytest_unconfigure(config: pytest.Config) -> None:
    """Best-effort cleanup applies only to a path generated by this plugin."""

    basetemp = config.stash.get(_GENERATED_BASETEMP, None)
    if basetemp is not None:
        rmtree(basetemp, ignore_errors=True)
